### ISSUE TITLE
Add ability to manage ssl certs

### ISSUE THREAD

**Issue by jmhertlein** [jmhertlein/yog#3]
Maybe a new file: cas.yml or something. This defines where the private key is stored + an ident for the CA. 

Then in necronomicons, you can say:

```
certs:
    - ca: my-ca-ident
      cn: [names]
      [...] etc [...]
      storage: /secrets/...
```

Then when you yog the host, if needed, it'll pull the private key from the ca location to generate the client cert and place it.

Will need a new yog command, perhaps, to handle creating the CA. Or maybe it can just be defined in the necronomicon.

```
cas:
    - ident: my-ident
      storage: /secrets/...
```
